// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider"; // Corrected path
import { NavBar, Footer } from "@/components/layout";
import { UserProvider } from '@auth0/nextjs-auth0/client'; // Import UserProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RediGNN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <UserProvider> {/* Wrap with UserProvider */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col min-h-screen">
              <NavBar />
              <main className="flex-grow pt-16 container mx-auto">
                {children}
              </main>
              <Footer />
            </div>
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}